import React, { useState } from 'react';

import styles from './App.module.scss';

import {
  Treebank,
  Sentence,
  Text,
  Graph,
  Information,
  Xml,
  Collapse,
  Alignment,
  Original,
  Translation,
} from '../../lib';

const xml = '<treebank xml:lang="grc" format="aldt" version="1.5">\n'
  + '   <date>Thu Aug 21 19:31:06 +0000 2014</date>\n'
  + '   <annotator>\n'
  + '     <short/>\n'
  + '     <name/>\n'
  + '     <address/>\n'
  + '     <uri>http://services.perseids.org/llt/segtok</uri>\n'
  + '   </annotator>\n'
  + '   <annotator>\n'
  + '     <short/>\n'
  + '     <name/>\n'
  + '     <address/>\n'
  + '     <uri>http://github.com/latin-language-toolkit/arethusa</uri>\n'
  + '   </annotator>\n'
  + '   <annotator>\n'
  + '     <short>Vanessa Gorman</short>\n'
  + '     <name>Vanessa Gorman</name>\n'
  + '     <address>vbgorman@gmail.com</address>\n'
  + '     <uri>\n'
  + '       http://data.perseus.org/sosol/users/Vanessa%20Gorman\n'
  + '     </uri>\n'
  + '   </annotator>\n'
  + '      <sentence id="1" subdoc="1.1-1.7" document_id="urn:cts:greekLit:tlg0012.tlg001.perseus-grc1">\n'
  + '        <word id="1" form="μῆνιν" lemma="μῆνις" postag="n-s---fa-" relation="OBJ" cite="urn:cts:greekLit:tlg0012.tlg001:1.1" head="2" gloss="wrath, anger" />\n'
  + '        <word id="2" form="ἄειδε" lemma="ἀείδω" postag="v2spma---" relation="PRED_CO" cite="urn:cts:greekLit:tlg0012.tlg001:1.1" head="32" gloss="sing" />\n'
  + '        <word id="3" form="θεὰ" lemma="θεά" postag="n-s---fv-" relation="ExD" cite="urn:cts:greekLit:tlg0012.tlg001:1.1" head="2" notes="θεά, the Μοῦσα of Od. 1.1, who tells the poet the history which he has to relate; see 2.484-92, and compare Od. 22.347 αὐτοδίδακτος δ\' εἰμί, θεὸς δέ μοι ἐν φρεσὶν οἰμας παντοίας ἐνέφυσεν, and Od. 8.44, 64, 488 ἢ σέ γε Μοῦσ\' ἐδίδαξε, Διὸς πάϊς, ἢ σέ γ\' Ἀπόλλων." gloss="goddess" />\n'
  + '        <word id="4" form="Πηληϊάδεω" lemma="Πηληιάδης" postag="n-s---mg-" relation="ATR" cite="urn:cts:greekLit:tlg0012.tlg001:1.1" head="5" notes="Πηληϊάδεω, originally no doubt Πηληϊάδα\'(ο). This is one of a class of patronymics formed with a double suffix, the adjectival -ιο- and the purely patronymic -αδη-ς: while the commoner form Πηλε-ίδη-ς has only one. Cf. 2.566." />\n'
  + '        <word id="5" form="Ἀχιλῆος" lemma="Ἀχιλλεύς" postag="n-s---mg-" relation="ATR" cite="urn:cts:greekLit:tlg0012.tlg001:1.1" head="1" gloss="Achilles" />\n'
  + '        <word id="6" form="οὐλομένην" lemma="οὐλόμενος" postag="a-s---fa-" relation="ATR" cite="urn:cts:greekLit:tlg0012.tlg001:1.2" head="1" notes="οὐλομένην, accursed; it bears the same relation to the curse ὄλοιο as ὀνήμενος (Od. 2.33) to the blessing ὄναιο, and means \'that of which we say ὄλοιο.\' It is best regarded as a purely metrical variant of ὀλόμενος, which occurs in the same sense in Trag. (Eur. Hel. 231 , Eur. Phoen. 1029, Eur. Or. 1363, Eur. Herc. 1061); see Schulze Qu. Ep. pp. 192 ff." gloss="destructive, baneful" />\n'
  + '        <word id="7" form="," lemma="," postag="u--------" relation="AuxX" cite="" head="23"/>\n'
  + '        <word id="8" form="ἣ" lemma="ὅς" postag="p-s---fn-" relation="SBJ" cite="urn:cts:greekLit:tlg0012.tlg001:1.2" head="23" gloss="who, which, that" />\n'
  + '        <word id="9" form="μυρί\'" lemma="μυρίος" postag="a-p---na-" relation="ATR" cite="urn:cts:greekLit:tlg0012.tlg001:1.2" head="11" notes="μυρία, countless; in its later sense, 10,000, the word is accented μύριοι." gloss="countless" />\n'
  + '        <word id="10" form="Ἀχαιοῖς" lemma="Ἀχαιός" postag="a-p---md-" relation="OBJ" cite="urn:cts:greekLit:tlg0012.tlg001:1.2" head="12" gloss="Achaian" />\n'
  + '        <word id="11" form="ἄλγε\'" lemma="ἄλγος" postag="n-p---na-" relation="OBJ" cite="urn:cts:greekLit:tlg0012.tlg001:1.2" head="12" gloss="pain" />\n'
  + '        <word id="12" form="ἔθηκε" lemma="τίθημι" postag="v3saia---" relation="ATR_CO" cite="urn:cts:greekLit:tlg0012.tlg001:1.2" head="23" gloss="put" />\n'
  + '        <word id="13" form="," lemma="," postag="u--------" relation="AuxX" cite="" head="23"/>\n'
  + '        <word id="14" form="πολλὰς" lemma="πολύς" postag="a-p---fa-" relation="ATR" cite="urn:cts:greekLit:tlg0012.tlg001:1.3" head="17" gloss="many" />\n'
  + '        <word id="15" form="δ\'" lemma="δέ" postag="g--------" relation="AuxY" cite="urn:cts:greekLit:tlg0012.tlg001:1.3" head="23" gloss="and, but" />\n'
  + '        <word id="16" form="ἰφθίμους" lemma="ἴφθιμος" postag="a-p---ma-" relation="ATR" cite="urn:cts:greekLit:tlg0012.tlg001:1.3" head="17" notes="ἴφθιμος here, as in 24 other places (Knös), does not admit an initial ϝ and never requires it. Thus connexion with ϝίς, ϝίφιος is impossible, in spite of the nearness of sense. For a suggested etymology see Collitz in AJP. viii. 214-7. The feminine ἰφθίμη is also found, but only applied to women-e.g. 19.116." gloss="stout, strong, stalwart" />\n'
  + '        <word id="17" form="ψυχὰς" lemma="ψυχή" postag="n-p---fa-" relation="OBJ" cite="urn:cts:greekLit:tlg0012.tlg001:1.3" head="19" gloss="breath" />\n'
  + '        <word id="18" form="Ἄϊδι" lemma="Αἵδης" postag="n-s---md-" relation="OBJ" cite="urn:cts:greekLit:tlg0012.tlg001:1.3" head="19" notes="Ἄϊδι, a metaplastic dative of Ἀΐδης, which in H. always means the god, not his realm-with the exception, apparently, of 23.244."/>\n'
  + '        <word id="19" form="προΐαψεν" lemma="προιάπτω" postag="v3saia---" relation="ATR_CO" cite="urn:cts:greekLit:tlg0012.tlg001:1.3" head="23" notes="προΐαψε: προ implies \'forth on their way,\' as in προπέμπειν, προιέναι (195, 442, etc.). ἰαπ- = iac-, so that προΐαψεν = pro-iec-it exactly." gloss="to send forward, to send untimely" />\n'
  + '        <word id="20" form="ἡρώων" lemma="ἥρως" postag="n-p---mg-" relation="ATR" cite="urn:cts:greekLit:tlg0012.tlg001:1.4" head="17" gloss="hero" />\n'
  + '        <word id="21" form="," lemma="," postag="u--------" relation="AuxX" cite="" head="23"/>\n'
  + '        <word id="22" form="αὐτοὺς" lemma="αὐτός" postag="a-p---ma-" relation="OBJ" cite="urn:cts:greekLit:tlg0012.tlg001:1.4" head="25" notes="αὐτούς: the body is to Homer the real self, the ψυχή is a mere shadow; cf. 23.65, where the soul of Patroklos is πάντ\' αὐτῶι εἰκυῖα, like the real man." gloss="self , same, s/he/it" />\n'
  + '        <word id="23" form="δὲ" lemma="δέ" postag="g--------" relation="COORD" cite="urn:cts:greekLit:tlg0012.tlg001:1.4" head="1" gloss="and, but" />\n'
  + '        <word id="24" form="ἑλώρια" lemma="ἑλώριον" postag="n-p---na-" relation="OCOMP" cite="urn:cts:greekLit:tlg0012.tlg001:1.4" head="25" gloss="booty, spoil, prey" />\n'
  + '        <word id="25" form="τεῦχε" lemma="τεύχω" postag="v3siia---" relation="ATR_CO" cite="urn:cts:greekLit:tlg0012.tlg001:1.4" head="23" gloss="build"/>\n'
  + '        <word id="26" form="κύνεσσιν" lemma="κύων" postag="n-p---md-" relation="OBJ_CO" cite="urn:cts:greekLit:tlg0012.tlg001:1.4" head="28" gloss="dog" />\n'
  + '        <word id="27" form="οἰωνοῖσί" lemma="οἰωνός" postag="n-p---md-" relation="OBJ_CO" cite="urn:cts:greekLit:tlg0012.tlg001:1.5" head="28" gloss="a large bird, bird of prey" />\n'
  + '        <word id="28" form="τε" lemma="τε" postag="g--------" relation="COORD" cite="urn:cts:greekLit:tlg0012.tlg001:1.5" head="25" gloss="and" />\n'
  + '        <word id="29" form="πᾶσι" lemma="πᾶς" postag="a-p---md-" relation="ATR" cite="urn:cts:greekLit:tlg0012.tlg001:1.5" head="27" notes="πᾶσι, i.e. all that chose to come: a perfectly natural expression. The reading δαῖτα ascribed to Zen. is not mentioned in the scholia, which merely say that he athetized 4-5. The only authority for the statement is Athenaeus (i. p. 12), on whom no reliance can be placed. But the reading is in itself vigorous and poetical. In fact the metaphor is so natural that we cannot even argue with confidence that Aischylos had δαῖτα before him when he wrote (Supp. 800) κυσὶν δ\' ἔπειθ\' ἕλωρα κἀπιχωρίοις | ὄρνισι δεῖπνον οὐκ ἀναίνομαι πελεῖν: or Eur. Hec. 1077 σφακτὰν κυσί τε φονίαν δαῖτ\' ἀνήμερον, Ion 505 πτανοῖς ἐξώρισε θοίναν θηρσί τε φοινίαν δαῖτα (Soph. is neutral, Aj. 830 ῥιφθῶ κυσὶν πρόβλητος οἰωνοῖς θ\' ἕλωρ). In all these cases there is an apparent echo of the present passage, and δαῖτα if a real variant is much older than Zen. The argument against it in Athenaeus (often ascribed, though without ground, to Ar.), that H. never uses δαίς except of human banquets, is not even based on fact, see 24.43. On the whole δαῖτα seems intrinsically a better reading, but we have no right to leave the uniform tradition of the MSS." gloss="all" />\n'
  + '        <word id="30" form="," lemma="," postag="u--------" relation="AuxX" cite="" head="32"/>\n'
  + '        <word id="31" form="Διὸς" lemma="Ζεύς" postag="n-s---mg-" relation="ATR" cite="urn:cts:greekLit:tlg0012.tlg001:1.5" head="34" gloss="Zeus" />\n'
  + '        <word id="32" form="δ\'" lemma="δέ" postag="g--------" relation="COORD" cite="urn:cts:greekLit:tlg0012.tlg001:1.5" head="0" gloss="and, but" />\n'
  + '        <word id="33" form="ἐτελείετο" lemma="τελέω" postag="v3siie---" relation="PRED_CO" cite="urn:cts:greekLit:tlg0012.tlg001:1.5" head="32" gloss="fulfil" />\n'
  + '        <word id="34" form="βουλή" lemma="βουλή" postag="n-s---fn-" relation="SBJ" cite="urn:cts:greekLit:tlg0012.tlg001:1.5" head="33" gloss="plan, council" />\n'
  + '        <word id="35" form="," lemma="," postag="u--------" relation="AuxX" cite="" head="41"/>\n'
  + '        <word id="36" form="ἐξ" lemma="ἐκ" postag="r--------" relation="AuxP" cite="urn:cts:greekLit:tlg0012.tlg001:1.6" head="41" notes="ἐξ οὗ may refer to the preceding line, \'the will of Zeus was being fulfilled from the time when\' (so Ar.); or better, to ἄειδε in the first line, \'take up the song from the point when,\' as in Od. 8.500 φαῖνε δ\' ἀοιδήν, ἔνθεν ἑλών, ὡς οἱ μέν, κτλ. The extraordinary variant διὰ στήτην (ἐρίσαντο) was explained to mean \'on account of a woman\' (!)" gloss="+ gen from, out of" />\n'
  + '        <word id="37" form="οὗ" lemma="ὅς" postag="p-s---mg-" relation="ADV" cite="urn:cts:greekLit:tlg0012.tlg001:1.6" head="36" notes="ἐξ οὗ may refer to the preceding line, \'the will of Zeus was being fulfilled from the time when\' (so Ar.); or better, to ἄειδε in the first line, \'take up the song from the point when,\' as in Od. 8.500 φαῖνε δ\' ἀοιδήν, ἔνθεν ἑλών, ὡς οἱ μέν, κτλ. The extraordinary variant διὰ στήτην (ἐρίσαντο) was explained to mean \'on account of a woman\' (!)" gloss="who, which, that" />\n'
  + '        <word id="38" form="δὴ" lemma="δή" postag="g--------" relation="AuxY" cite="urn:cts:greekLit:tlg0012.tlg001:1.6" head="41" gloss="now" />\n'
  + '        <word id="39" form="τὰ" lemma="ὁ" postag="l-p---na-" relation="ATR" cite="urn:cts:greekLit:tlg0012.tlg001:1.6" head="40" gloss="the" />\n'
  + '        <word id="40" form="πρῶτα" lemma="πρῶτος" postag="a-p---na-" relation="ADV" cite="urn:cts:greekLit:tlg0012.tlg001:1.6" head="41" gloss="first" />\n'
  + '        <word id="41" form="διαστήτην" lemma="διίστημι" postag="v3daia---" relation="ADV" cite="urn:cts:greekLit:tlg0012.tlg001:1.6" head="33" gloss="to set apart, to place separately, separate" />\n'
  + '        <word id="42" form="ἐρίσαντε" lemma="ἐρίζω" postag="v-dapamn-" relation="ADV" cite="urn:cts:greekLit:tlg0012.tlg001:1.6" head="41" gloss="to strive, wrangle, quarrel" />\n'
  + '        <word id="43" form="Ἀτρεΐδης" lemma="Ἀτρείδης" postag="n-s---mn-" relation="SBJ_CO" cite="urn:cts:greekLit:tlg0012.tlg001:1.7" head="47"/>\n'
  + '        <word id="44" form="τε" lemma="τε" postag="g--------" relation="AuxY" cite="urn:cts:greekLit:tlg0012.tlg001:1.7" head="47" gloss="and" />\n'
  + '        <word id="45" form="ἄναξ" lemma="ἄναξ" postag="n-s---mn-" relation="ATR" cite="urn:cts:greekLit:tlg0012.tlg001:1.7" head="43" gloss="ruler, lord" />\n'
  + '        <word id="46" form="ἀνδρῶν" lemma="ἀνήρ" postag="n-p---mg-" relation="ATR" cite="urn:cts:greekLit:tlg0012.tlg001:1.7" head="45" gloss="man" />\n'
  + '        <word id="47" form="καὶ" lemma="καί" postag="c--------" relation="COORD" cite="urn:cts:greekLit:tlg0012.tlg001:1.7" head="41" gloss="and" />\n'
  + '        <word id="48" form="δῖος" lemma="δῖος" postag="a-s---mn-" relation="ATR" cite="urn:cts:greekLit:tlg0012.tlg001:1.7" head="49" gloss="divine" />\n'
  + '        <word id="49" form="Ἀχιλλεύς" lemma="Ἀχιλλεύς" postag="n-s---mn-" relation="SBJ_CO" cite="urn:cts:greekLit:tlg0012.tlg001:1.7" head="47" gloss="Achilles" />\n'
  + '        <word id="50" form="." lemma="." postag="u--------" relation="AuxK" cite="" head="0"/>\n'
  + '      </sentence>\n'
  + ' </treebank>';

const alignment = '<aligned-text xmlns="http://alpheios.net/namespaces/aligned-text">\n'
  + '  <language lnum="L1" xml:lang="grc" dir="ltr"/>\n'
  + '  <language lnum="L2" xml:lang="eng" dir="ltr"/>\n'
  + '  <comment class="title">Iliad 1.1-7</comment>\n'
  + '  <sentence id="1" document_id="">\n'
  + '    <wds lnum="L1">\n'
  + '      <comment class="uri"/>\n'
  + '      <w n="1-1" id="1">\n'
  + '        <text>μῆνιν</text>\n'
  + '        <refs nrefs="1-1 1-2"/>\n'
  + '      </w>\n'
  + '      <w n="1-2" id="2">\n'
  + '        <text>ἄειδε</text>\n'
  + '        <refs nrefs="1-3 1-7"/>\n'
  + '      </w>\n'
  + '      <w n="1-3" id="3">\n'
  + '        <text>θεὰ</text>\n'
  + '        <refs nrefs="1-5"/>\n'
  + '      </w>\n'
  + '      <w n="1-4" id="4">\n'
  + '        <text>Πηληϊάδεω</text>\n'
  + '        <refs nrefs="1-8 1-9 1-10"/>\n'
  + '      </w>\n'
  + '      <w n="1-5" id="5">\n'
  + '        <text>Ἀχιλῆος</text>\n'
  + '        <refs nrefs="1-12"/>\n'
  + '      </w>\n'
  + '      <w n="" id="5-1">\n'
  + '        <text>\n</text>\n'
  + '      </w>\n'
  + '      <w n="1-6" id="6">\n'
  + '        <text>οὐλομένην</text>\n'
  + '        <refs nrefs="1-14 1-15 1-16"/>\n'
  + '      </w>\n'
  + '      <w n="1-7" id="7">\n'
  + '        <text>,</text>\n'
  + '      </w>\n'
  + '      <w n="1-8" id="8">\n'
  + '        <text>ἣ</text>\n'
  + '        <refs nrefs="1-17"/>\n'
  + '      </w>\n'
  + '      <w n="1-9" id="9">\n'
  + '        <text>μυρί᾽</text>\n'
  + '        <refs nrefs="1-19"/>\n'
  + '      </w>\n'
  + '      <w n="1-10" id="10">\n'
  + '        <text>Ἀχαιοῖς</text>\n'
  + '        <refs nrefs="1-21 1-22 1-23"/>\n'
  + '      </w>\n'
  + '      <w n="1-11" id="11">\n'
  + '        <text>ἄλγε᾽</text>\n'
  + '        <refs nrefs="1-20"/>\n'
  + '      </w>\n'
  + '      <w n="1-12" id="12">\n'
  + '        <text>ἔθηκε</text>\n'
  + '        <refs nrefs="1-18"/>\n'
  + '      </w>\n'
  + '      <w n="1-13" id="13">\n'
  + '        <text>,</text>\n'
  + '      </w>\n'
  + '      <w n="" id="12-1">\n'
  + '        <text>\n</text>\n'
  + '      </w>\n'
  + '      <w n="1-14" id="14">\n'
  + '        <text>πολλὰς</text>\n'
  + '        <refs nrefs="1-30"/>\n'
  + '      </w>\n'
  + '      <w n="1-15" id="15">\n'
  + '        <text>δ᾽</text>\n'
  + '        <refs nrefs="1-25"/>\n'
  + '      </w>\n'
  + '      <w n="1-16" id="16">\n'
  + '        <text>ἰφθίμους</text>\n'
  + '        <refs nrefs="1-31"/>\n'
  + '      </w>\n'
  + '      <w n="1-17" id="17">\n'
  + '        <text>ψυχὰς</text>\n'
  + '        <refs nrefs="1-32"/>\n'
  + '      </w>\n'
  + '      <w n="1-18" id="18">\n'
  + '        <text>Ἄϊδι</text>\n'
  + '        <refs nrefs="1-28 1-29"/>\n'
  + '      </w>\n'
  + '      <w n="1-19" id="19">\n'
  + '        <text>προΐαψεν</text>\n'
  + '        <refs nrefs="1-26 1-27"/>\n'
  + '      </w>\n'
  + '      <w n="" id="19-1">\n'
  + '        <text>\n</text>\n'
  + '      </w>\n'
  + '      <w n="1-20" id="20">\n'
  + '        <text>ἡρώων</text>\n'
  + '        <refs nrefs="1-33 1-34"/>\n'
  + '      </w>\n'
  + '      <w n="1-21" id="21">\n'
  + '        <text>,</text>\n'
  + '      </w>\n'
  + '      <w n="1-22" id="22">\n'
  + '        <text>αὐτοὺς</text>\n'
  + '        <refs nrefs="1-38 1-39"/>\n'
  + '      </w>\n'
  + '      <w n="1-23" id="23">\n'
  + '        <text>δὲ</text>\n'
  + '        <refs nrefs="1-36"/>\n'
  + '      </w>\n'
  + '      <w n="1-24" id="24">\n'
  + '        <text>ἑλώρια</text>\n'
  + '        <refs nrefs="1-40"/>\n'
  + '      </w>\n'
  + '      <w n="1-25" id="25">\n'
  + '        <text>τεῦχε</text>\n'
  + '        <refs nrefs="1-37"/>\n'
  + '      </w>\n'
  + '      <w n="1-26" id="26">\n'
  + '        <text>κύνεσσιν</text>\n'
  + '        <refs nrefs="1-41 1-42"/>\n'
  + '      </w>\n'
  + '      <w n="" id="26-1">\n'
  + '        <text>\n</text>\n'
  + '      </w>\n'
  + '      <w n="1-27" id="27">\n'
  + '        <text>οἰωνοῖσί</text>\n'
  + '        <refs nrefs="1-45"/>\n'
  + '      </w>\n'
  + '      <w n="1-28" id="28">\n'
  + '        <text>τε</text>\n'
  + '        <refs nrefs="1-43"/>\n'
  + '      </w>\n'
  + '      <w n="1-29" id="29">\n'
  + '        <text>πᾶσι</text>\n'
  + '        <refs nrefs="1-44"/>\n'
  + '      </w>\n'
  + '      <w n="1-30" id="30">\n'
  + '        <text>,</text>\n'
  + '      </w>\n'
  + '      <w n="1-31" id="31">\n'
  + '        <text>Διὸς</text>\n'
  + '        <refs nrefs="2-4 2-5"/>\n'
  + '      </w>\n'
  + '      <w n="1-32" id="32">\n'
  + '        <text>δ᾽</text>\n'
  + '        <refs nrefs="2-1"/>\n'
  + '      </w>\n'
  + '      <w n="1-33" id="33">\n'
  + '        <text>ἐτελείετο</text>\n'
  + '        <refs nrefs="2-6 2-7 2-8"/>\n'
  + '      </w>\n'
  + '      <w n="1-34" id="34">\n'
  + '        <text>βουλή</text>\n'
  + '        <refs nrefs="2-2 2-3"/>\n'
  + '      </w>\n'
  + '      <w n="1-35" id="35">\n'
  + '        <text>,</text>\n'
  + '      </w>\n'
  + '      <w n="" id="34-1">\n'
  + '        <text>\n</text>\n'
  + '      </w>\n'
  + '      <w n="1-36" id="36">\n'
  + '        <text>ἐξ</text>\n'
  + '        <refs nrefs="2-10"/>\n'
  + '      </w>\n'
  + '      <w n="1-37" id="37">\n'
  + '        <text>οὗ</text>\n'
  + '        <refs nrefs="2-11 2-12 2-13"/>\n'
  + '      </w>\n'
  + '      <w n="1-38" id="38">\n'
  + '        <text>δὴ</text>\n'
  + '      </w>\n'
  + '      <w n="1-39" id="39">\n'
  + '        <text>τὰ</text>\n'
  + '        <refs nrefs="2-14"/>\n'
  + '      </w>\n'
  + '      <w n="1-40" id="40">\n'
  + '        <text>πρῶτα</text>\n'
  + '        <refs nrefs="2-14"/>\n'
  + '      </w>\n'
  + '      <w n="1-41" id="41">\n'
  + '        <text>διαστήτην</text>\n'
  + '        <refs nrefs="2-15 2-16"/>\n'
  + '      </w>\n'
  + '      <w n="1-42" id="42">\n'
  + '        <text>ἐρίσαντε</text>\n'
  + '        <refs nrefs="2-17 2-18"/>\n'
  + '      </w>\n'
  + '      <w n="" id="42-1">\n'
  + '        <text>\n</text>\n'
  + '      </w>\n'
  + '      <w n="1-43" id="43">\n'
  + '        <text>Ἀτρεΐδης</text>\n'
  + '        <refs nrefs="2-19 2-20 2-21"/>\n'
  + '      </w>\n'
  + '      <w n="1-44" id="44">\n'
  + '        <text>τε</text>\n'
  + '        <refs nrefs="2-27"/>\n'
  + '      </w>\n'
  + '      <w n="1-45" id="45">\n'
  + '        <text>ἄναξ</text>\n'
  + '        <refs nrefs="2-23"/>\n'
  + '      </w>\n'
  + '      <w n="1-46" id="46">\n'
  + '        <text>ἀνδρῶν</text>\n'
  + '        <refs nrefs="2-24 2-25"/>\n'
  + '      </w>\n'
  + '      <w n="1-47" id="47">\n'
  + '        <text>καὶ</text>\n'
  + '        <refs nrefs="2-27"/>\n'
  + '      </w>\n'
  + '      <w n="1-48" id="48">\n'
  + '        <text>δῖος</text>\n'
  + '        <refs nrefs="2-28"/>\n'
  + '      </w>\n'
  + '      <w n="1-49" id="49">\n'
  + '        <text>Ἀχιλλεύς</text>\n'
  + '        <refs nrefs="2-29"/>\n'
  + '      </w>\n'
  + '      <w n="1-50" id="50">\n'
  + '        <text>.</text>\n'
  + '      </w>\n'
  + '    </wds>\n'
  + '    <wds lnum="L2">\n'
  + '      <comment class="uri"/>\n'
  + '      <w n="1-1">\n'
  + '        <text>The</text>\n'
  + '        <refs nrefs="1-1"/>\n'
  + '      </w>\n'
  + '      <w n="1-2">\n'
  + '        <text>wrath</text>\n'
  + '        <refs nrefs="1-1"/>\n'
  + '      </w>\n'
  + '      <w n="1-3">\n'
  + '        <text>sing</text>\n'
  + '        <refs nrefs="1-2"/>\n'
  + '      </w>\n'
  + '      <w n="1-4">\n'
  + '        <text>,</text>\n'
  + '      </w>\n'
  + '      <w n="1-5">\n'
  + '        <text>goddess</text>\n'
  + '        <refs nrefs="1-3"/>\n'
  + '      </w>\n'
  + '      <w n="1-6">\n'
  + '        <text>,</text>\n'
  + '      </w>\n'
  + '      <w n="1-7">\n'
  + '        <text>of</text>\n'
  + '        <refs nrefs="1-2"/>\n'
  + '      </w>\n'
  + '      <w n="1-8">\n'
  + '        <text>Peleus</text>\n'
  + '        <refs nrefs="1-4"/>\n'
  + '      </w>\n'
  + '      <w n="1-9">\n'
  + '        <text>\'</text>\n'
  + '        <refs nrefs="1-4"/>\n'
  + '      </w>\n'
  + '      <w n="1-10">\n'
  + '        <text>son</text>\n'
  + '        <refs nrefs="1-4"/>\n'
  + '      </w>\n'
  + '      <w n="1-11">\n'
  + '        <text>,</text>\n'
  + '      </w>\n'
  + '      <w n="1-12">\n'
  + '        <text>Achilles</text>\n'
  + '        <refs nrefs="1-5"/>\n'
  + '      </w>\n'
  + '      <w n="1-13">\n'
  + '        <text>,</text>\n'
  + '      </w>\n'
  + '      <w n="1-14">\n'
  + '        <text>that</text>\n'
  + '        <refs nrefs="1-6"/>\n'
  + '      </w>\n'
  + '      <w n="1-15">\n'
  + '        <text>destructive</text>\n'
  + '        <refs nrefs="1-6"/>\n'
  + '      </w>\n'
  + '      <w n="1-16">\n'
  + '        <text>wrath</text>\n'
  + '        <refs nrefs="1-6"/>\n'
  + '      </w>\n'
  + '      <w n="1-17">\n'
  + '        <text>which</text>\n'
  + '        <refs nrefs="1-8"/>\n'
  + '      </w>\n'
  + '      <w n="1-18">\n'
  + '        <text>brought</text>\n'
  + '        <refs nrefs="1-12"/>\n'
  + '      </w>\n'
  + '      <w n="1-19">\n'
  + '        <text>countless</text>\n'
  + '        <refs nrefs="1-9"/>\n'
  + '      </w>\n'
  + '      <w n="1-20">\n'
  + '        <text>woes</text>\n'
  + '        <refs nrefs="1-11"/>\n'
  + '      </w>\n'
  + '      <w n="1-21">\n'
  + '        <text>upon</text>\n'
  + '        <refs nrefs="1-10"/>\n'
  + '      </w>\n'
  + '      <w n="1-22">\n'
  + '        <text>the</text>\n'
  + '        <refs nrefs="1-10"/>\n'
  + '      </w>\n'
  + '      <w n="1-23">\n'
  + '        <text>Achaeans</text>\n'
  + '        <refs nrefs="1-10"/>\n'
  + '      </w>\n'
  + '      <w n="1-24">\n'
  + '        <text>,</text>\n'
  + '      </w>\n'
  + '      <w n="1-25">\n'
  + '        <text>and</text>\n'
  + '        <refs nrefs="1-15"/>\n'
  + '      </w>\n'
  + '      <w n="1-26">\n'
  + '        <text>sent</text>\n'
  + '        <refs nrefs="1-19"/>\n'
  + '      </w>\n'
  + '      <w n="1-27">\n'
  + '        <text>forth</text>\n'
  + '        <refs nrefs="1-19"/>\n'
  + '      </w>\n'
  + '      <w n="1-28">\n'
  + '        <text>to</text>\n'
  + '        <refs nrefs="1-18"/>\n'
  + '      </w>\n'
  + '      <w n="1-29">\n'
  + '        <text>Hades</text>\n'
  + '        <refs nrefs="1-18"/>\n'
  + '      </w>\n'
  + '      <w n="1-30">\n'
  + '        <text>many</text>\n'
  + '        <refs nrefs="1-14"/>\n'
  + '      </w>\n'
  + '      <w n="1-31">\n'
  + '        <text>valiant</text>\n'
  + '        <refs nrefs="1-16"/>\n'
  + '      </w>\n'
  + '      <w n="1-32">\n'
  + '        <text>souls</text>\n'
  + '        <refs nrefs="1-17"/>\n'
  + '      </w>\n'
  + '      <w n="1-33">\n'
  + '        <text>of</text>\n'
  + '        <refs nrefs="1-20"/>\n'
  + '      </w>\n'
  + '      <w n="1-34">\n'
  + '        <text>heroes</text>\n'
  + '        <refs nrefs="1-20"/>\n'
  + '      </w>\n'
  + '      <w n="1-35">\n'
  + '        <text>,</text>\n'
  + '      </w>\n'
  + '      <w n="1-36">\n'
  + '        <text>and</text>\n'
  + '        <refs nrefs="1-23"/>\n'
  + '      </w>\n'
  + '      <w n="1-37">\n'
  + '        <text>made</text>\n'
  + '        <refs nrefs="1-25"/>\n'
  + '      </w>\n'
  + '      <w n="1-38">\n'
  + '        <text>them</text>\n'
  + '        <refs nrefs="1-22"/>\n'
  + '      </w>\n'
  + '      <w n="1-39">\n'
  + '        <text>themselves</text>\n'
  + '        <refs nrefs="1-22"/>\n'
  + '      </w>\n'
  + '      <w n="1-40">\n'
  + '        <text>spoil</text>\n'
  + '        <refs nrefs="1-24"/>\n'
  + '      </w>\n'
  + '      <w n="1-41">\n'
  + '        <text>for</text>\n'
  + '        <refs nrefs="1-26"/>\n'
  + '      </w>\n'
  + '      <w n="1-42">\n'
  + '        <text>dogs</text>\n'
  + '        <refs nrefs="1-26"/>\n'
  + '      </w>\n'
  + '      <w n="1-43">\n'
  + '        <text>and</text>\n'
  + '        <refs nrefs="1-28"/>\n'
  + '      </w>\n'
  + '      <w n="1-44">\n'
  + '        <text>every</text>\n'
  + '        <refs nrefs="1-29"/>\n'
  + '      </w>\n'
  + '      <w n="1-45">\n'
  + '        <text>bird</text>\n'
  + '        <refs nrefs="1-27"/>\n'
  + '      </w>\n'
  + '      <w n="1-46">\n'
  + '        <text>;</text>\n'
  + '      </w>\n'
  + '      <w n="2-1">\n'
  + '        <text>thus</text>\n'
  + '        <refs nrefs="1-32"/>\n'
  + '      </w>\n'
  + '      <w n="2-2">\n'
  + '        <text>the</text>\n'
  + '        <refs nrefs="1-34"/>\n'
  + '      </w>\n'
  + '      <w n="2-3">\n'
  + '        <text>plan</text>\n'
  + '        <refs nrefs="1-34"/>\n'
  + '      </w>\n'
  + '      <w n="2-4">\n'
  + '        <text>of</text>\n'
  + '        <refs nrefs="1-31"/>\n'
  + '      </w>\n'
  + '      <w n="2-5">\n'
  + '        <text>Zeus</text>\n'
  + '        <refs nrefs="1-31"/>\n'
  + '      </w>\n'
  + '      <w n="2-6">\n'
  + '        <text>came</text>\n'
  + '        <refs nrefs="1-33"/>\n'
  + '      </w>\n'
  + '      <w n="2-7">\n'
  + '        <text>to</text>\n'
  + '        <refs nrefs="1-33"/>\n'
  + '      </w>\n'
  + '      <w n="2-8">\n'
  + '        <text>fulfillment</text>\n'
  + '        <refs nrefs="1-33"/>\n'
  + '      </w>\n'
  + '      <w n="2-9">\n'
  + '        <text>,</text>\n'
  + '      </w>\n'
  + '      <w n="2-10">\n'
  + '        <text>from</text>\n'
  + '        <refs nrefs="1-36"/>\n'
  + '      </w>\n'
  + '      <w n="2-11">\n'
  + '        <text>the</text>\n'
  + '        <refs nrefs="1-37"/>\n'
  + '      </w>\n'
  + '      <w n="2-12">\n'
  + '        <text>time</text>\n'
  + '        <refs nrefs="1-37"/>\n'
  + '      </w>\n'
  + '      <w n="2-13">\n'
  + '        <text>when</text>\n'
  + '        <refs nrefs="1-37"/>\n'
  + '      </w>\n'
  + '      <w n="2-14">\n'
  + '        <text>first</text>\n'
  + '        <refs nrefs="1-40"/>\n'
  + '      </w>\n'
  + '      <w n="2-15">\n'
  + '        <text>they</text>\n'
  + '        <refs nrefs="1-41"/>\n'
  + '      </w>\n'
  + '      <w n="2-16">\n'
  + '        <text>parted</text>\n'
  + '        <refs nrefs="1-41"/>\n'
  + '      </w>\n'
  + '      <w n="2-17">\n'
  + '        <text>in</text>\n'
  + '        <refs nrefs="1-42"/>\n'
  + '      </w>\n'
  + '      <w n="2-18">\n'
  + '        <text>strife</text>\n'
  + '        <refs nrefs="1-42"/>\n'
  + '      </w>\n'
  + '      <w n="2-19">\n'
  + '        <text>Atreus</text>\n'
  + '        <refs nrefs="1-43"/>\n'
  + '      </w>\n'
  + '      <w n="2-20">\n'
  + '        <text>\'</text>\n'
  + '        <refs nrefs="1-43"/>\n'
  + '      </w>\n'
  + '      <w n="2-21">\n'
  + '        <text>son</text>\n'
  + '        <refs nrefs="1-43"/>\n'
  + '      </w>\n'
  + '      <w n="2-22">\n'
  + '        <text>,</text>\n'
  + '      </w>\n'
  + '      <w n="2-23">\n'
  + '        <text>king</text>\n'
  + '        <refs nrefs="1-45"/>\n'
  + '      </w>\n'
  + '      <w n="2-24">\n'
  + '        <text>of</text>\n'
  + '        <refs nrefs="1-46"/>\n'
  + '      </w>\n'
  + '      <w n="2-25">\n'
  + '        <text>men</text>\n'
  + '        <refs nrefs="1-46"/>\n'
  + '      </w>\n'
  + '      <w n="2-26">\n'
  + '        <text>,</text>\n'
  + '      </w>\n'
  + '      <w n="2-27">\n'
  + '        <text>and</text>\n'
  + '        <refs nrefs="1-47"/>\n'
  + '      </w>\n'
  + '      <w n="2-28">\n'
  + '        <text>brilliant</text>\n'
  + '        <refs nrefs="1-48"/>\n'
  + '      </w>\n'
  + '      <w n="2-29">\n'
  + '        <text>Achilles</text>\n'
  + '        <refs nrefs="1-49"/>\n'
  + '      </w>\n'
  + '      <w n="2-30">\n'
  + '        <text>.</text>\n'
  + '      </w>\n'
  + '    </wds>\n'
  + '  </sentence>\n'
  + ' </aligned-text>';

import { xmlToJson } from '../../lib/utils/parsing';

const App = () => {
  return (
    <div className={styles.treebank}>
      <Treebank treebank={xml}>
        <Sentence id="1">
          <Alignment alignment={alignment}>
            <div className={styles.row}>
              <div className={styles.left}>
                <Original />
              </div>
              <div className={styles.right}>
                <Information field="gloss" />
                <Information />
                <Information field="notes" />
                <Collapse title="Translation">
                  <Translation />
                </Collapse>
                <Collapse title="Treebank">
                  <div className={styles.graph}>
                    <Graph />
                  </div>
                </Collapse>
                <Collapse title="XML">
                  <Xml />
                </Collapse>
              </div>
            </div>
          </Alignment>
        </Sentence>
      </Treebank>
    </div>
  );
};

export default App;
